CREATE DATABASE GUARDLLET


-------------------------------
-------------------------------
-- CREACION DE TABLAS ---------
-------------------------------
-------------------------------

CREATE TABLE DATOS(
	ID_DATOS INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	APELLIDO_P VARCHAR(50),
	APELLIDO_M	VARCHAR(50),
	CELULAR VARCHAR(10),
	BOLETA VARCHAR(10),
	GRUPO VARCHAR(6),
	FOTO VARCHAR(MAX),	
)

CREATE TABLE MONEDERO(
	ID_MONEDERO INT IDENTITY(1,1) PRIMARY KEY,
	SALDO VARCHAR(MAX),
	CODIGO VARCHAR(MAX),
)

CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	ID_MONEDERO INT,
	ID_DATOS INT,
	CORREO VARCHAR(100),
	CONTRASEÑA VARCHAR(300),
	TIPO_USUARIO INT,
	ESTADO INT,

	CONSTRAINT fk_DATOS_USUARIO FOREIGN KEY (ID_DATOS) REFERENCES DATOS (ID_DATOS),
	CONSTRAINT fk_MONEDERO_USUARIO FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO (ID_MONEDERO)
	
)

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	TIPO_PRODUCTO INT,
	PRECIO VARCHAR(MAX),
	FOTO VARCHAR(MAX),
	CODIGO VARCHAR(MAX),
)

CREATE TABLE MOVIMIENTO(
	ID_MOVIMIENTO INT IDENTITY(1,1) PRIMARY KEY,
	ID_MONEDERO INT,
	ID_PRODUCTO INT,
	TIPO_MOVIMIENTO INT,
	ESTADO INT,
	FECHA DATETIME,
	
	CONSTRAINT fk_MONEDERO_MOVIMIENTO FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO (ID_MONEDERO),
	CONSTRAINT fk_PRODUCTO_MOVIMIENTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
	
)

-------------------------------
-------------------------------
-- CREACION DE PROCEDIMIENTOS -
-------------------------------
-------------------------------



-- PROCEDIMIENTO DE LOGIN-----
------------------------------

CREATE PROCEDURE  [dbo].[LoginUsuario]
    
	@CORREO NVARCHAR(50), 
	@CONTRASEÑA NVARCHAR(50),
	@RESULTADO BIT OUTPUT

AS

	DECLARE @CONTRASEÑA_CODIFICADA AS NVARCHAR(300)
	DECLARE @CONTRASEÑA_DECODIFICADA AS NVARCHAR(50)

BEGIN

SELECT @CONTRASEÑA_CODIFICADA = CONTRASEÑA FROM USUARIO WHERE CORREO = @CORREO
Set @CONTRASEÑA_DECODIFICADA = DECRYPTBYPASSPHRASE('password', @CONTRASEÑA_CODIFICADA)

End

Begin

If @CONTRASEÑA_DECODIFICADA = @CONTRASEÑA
    Set @RESULTADO = 1
Else
    Set @RESULTADO = 0
    
End

---PROCEDIMIENTO PARA REGISTRAR-----
--------- USUARIO ------------------

CREATE PROCEDURE [dbo].[RegistroUsuario]

@ID_MONEDERO INT,
@ID_DATOS INT,
@CORREO VARCHAR(50),
@CONTRASEÑA VARCHAR(20),
@TIPO_USUARIO INT,
@ESTADO INT

AS

BEGIN
    
Insert Into USUARIO
(
    ID_MONEDERO,
	ID_DATOS,
	CORREO,
	CONTRASEÑA,
	TIPO_USUARIO,
	ESTADO
)

Values

(
	@ID_MONEDERO,
	@ID_DATOS,
	@CORREO,
	ENCRYPTBYPASSPHRASE('password', @CONTRASEÑA),
	@TIPO_USUARIO,
	@ESTADO
)

END

---PROCEDIMIENTO PARA REGISTRAR-----
------------ DATOS -----------------

CREATE PROCEDURE [dbo].[RegistroDatos]

@NOMBRE VARCHAR(100),
@APELLIDO_P VARCHAR(50),
@APELLIDO_M	VARCHAR(50),
@CELULAR VARCHAR(10),
@BOLETA VARCHAR(10),
@GRUPO VARCHAR(6),
@FOTO VARCHAR(MAX)

AS

BEGIN
    
Insert Into DATOS
(
    NOMBRE,
	APELLIDO_P,
	APELLIDO_M,
	CELULAR,
	BOLETA,
	GRUPO,
	FOTO
	
)

Values

(
	@NOMBRE,
	@APELLIDO_P,
	@APELLIDO_M,
	@CELULAR,
	@BOLETA,
	@GRUPO,
	@FOTO
)

END

---PROCEDIMIENTO PARA REGISTRAR-----
----------- MENEDERO ---------------

CREATE PROCEDURE [dbo].[RegistroMonedero]

@SALDO VARCHAR(MAX),
@CODIGO VARCHAR(MAX)

AS

BEGIN
    
Insert Into MONEDERO
(
    SALDO,
    CODIGO
	
)

Values

(
	@SALDO,
	@CODIGO
)

END