CREATE DATABASE GUARDLLET

GO

USE GUARDLLET

GO
-------------------------------
-------------------------------
-- CREACION DE TABLAS ---------
-------------------------------
-------------------------------

CREATE TABLE ESCUELAS(
	ID_ESCUELA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(200),
) 

CREATE TABLE DATOS(
	ID_DATOS INT IDENTITY(1,1) PRIMARY KEY,
	ID_ESCUELA INT,
	NOMBRE VARCHAR(100),
	APELLIDO_P VARCHAR(50),
	APELLIDO_M	VARCHAR(50),
	CELULAR VARCHAR(10),
	BOLETA VARCHAR(10),
	FOTO IMAGE,	
	
	CONSTRAINT fk_ESCUELA_DATOS FOREIGN KEY (ID_ESCUELA) REFERENCES ESCUELAS(ID_ESCUELA),
)

CREATE TABLE MONEDERO(
	ID_MONEDERO INT IDENTITY(1,1) PRIMARY KEY,
	SALDO VARCHAR(MAX),
	NUM_CODIGO VARCHAR(MAX),
	IMG_CODIGO IMAGE
)

CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	ID_MONEDERO INT,
	ID_DATOS INT,
	CORREO VARCHAR(100),
	CONTRASEÑA VARCHAR(300),
	CELULAR VARCHAR(10),
	TIPO_USUARIO INT,
	ESTADO INT,

	CONSTRAINT fk_DATOS_USUARIO FOREIGN KEY (ID_DATOS) REFERENCES DATOS (ID_DATOS),
	CONSTRAINT fk_MONEDERO_USUARIO FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO (ID_MONEDERO)
	
)

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	TIPO_PRODUCTO INT,
	PRECIO VARCHAR(MAX),
	FOTO VARCHAR(MAX),
	CODIGO VARCHAR(MAX),
)

CREATE TABLE MOVIMIENTO(
	ID_MOVIMIENTO INT IDENTITY(1,1) PRIMARY KEY,
	ID_MONEDERO INT,
	ID_PRODUCTO INT,
	TIPO_MOVIMIENTO INT,
	ESTADO INT,
	FECHA DATETIME,
	
	CONSTRAINT fk_MONEDERO_MOVIMIENTO FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO (ID_MONEDERO),
	CONSTRAINT fk_PRODUCTO_MOVIMIENTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
)

GO

-------------------------------
-------------------------------
-- CREACION DE PROCEDIMIENTOS -
-------------------------------
-------------------------------



-- PROCEDIMIENTO DE LOGIN-----
------------------------------

CREATE PROCEDURE  [dbo].[LoginUsuario]
    
	@CORREO VARCHAR(100), 
	@CONTRASEÑA VARCHAR(300),
	@RESULTADO BIT OUTPUT

AS

	DECLARE @CONTRASEÑA_CODIFICADA AS VARCHAR(300)
	DECLARE @CONTRASEÑA_DECODIFICADA AS VARCHAR(300)

BEGIN

SELECT @CONTRASEÑA_CODIFICADA = CONTRASEÑA FROM USUARIO WHERE CORREO = @CORREO
SET @CONTRASEÑA_DECODIFICADA = DECRYPTBYPASSPHRASE('password', @CONTRASEÑA_CODIFICADA)

END

BEGIN

IF @CONTRASEÑA_DECODIFICADA = @CONTRASEÑA
    SET @RESULTADO = 1
ELSE
    Set @RESULTADO = 0
    
END

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

GO

---PROCEDIMIENTO PARA REGISTRAR-----
--------- USUARIO ------------------

CREATE PROCEDURE [dbo].[RegistroUsuario]

@ID_MONEDERO INT,
@ID_DATOS INT,
@CORREO VARCHAR(50),
@CONTRASEÑA VARCHAR(20),
@CELULAR VARCHAR(10),
@TIPO_USUARIO INT,
@ESTADO INT

AS

BEGIN
    
Insert Into USUARIO
(
    ID_MONEDERO,
	ID_DATOS,
	CORREO,
	CONTRASEÑA,
	CELULAR,
	TIPO_USUARIO,
	ESTADO
)

Values

(
	@ID_MONEDERO,
	@ID_DATOS,
	@CORREO,
	ENCRYPTBYPASSPHRASE('password', @CONTRASEÑA),
	@CELULAR,
	@TIPO_USUARIO,
	@ESTADO
)

END

GO

---PROCEDIMIENTO PARA INICIALIZAR-----
------------ DATOS -----------------

CREATE PROCEDURE [dbo].[InicializarDatos]

@ID_ESCUELA INT,
@NOMBRE VARCHAR(100),
@APELLIDO_P VARCHAR(50),
@APELLIDO_M	VARCHAR(50),
@CELULAR VARCHAR(10),
@FOTO IMAGE

AS

BEGIN
    
Insert Into DATOS
(
	ID_ESCUELA,
    NOMBRE,
	APELLIDO_P,
	APELLIDO_M,
	CELULAR,
	FOTO
	
)

Values

(
	@ID_ESCUELA,
	@NOMBRE,
	@APELLIDO_P,
	@APELLIDO_M,
	@CELULAR,
	@FOTO
)

END

GO

CREATE PROCEDURE [dbo].[RegistroDatos]

@ID INT,
@ID_ESCUELA INT,
@NOMBRE VARCHAR(100),
@APELLIDO_P VARCHAR(50),
@APELLIDO_M	VARCHAR(50),
@BOLETA VARCHAR(10),
@FOTO IMAGE

AS

BEGIN
    
UPDATE DATOS 

SET
 
 ID_ESCUELA = @ID_ESCUELA,
 NOMBRE = @NOMBRE,
 APELLIDO_P = @APELLIDO_P,
 APELLIDO_M = @APELLIDO_M,
 BOLETA = @BOLETA,
 FOTO = @FOTO
 
WHERE ID_DATOS = @ID

END

GO

---PROCEDIMIENTO PARA REGISTRAR-----
----------- MENEDERO ---------------

CREATE PROCEDURE [dbo].[RegistroMonedero]

@SALDO VARCHAR(MAX),
@NUM_CODIGO VARCHAR(MAX),
@IMG_CODIGO IMAGE

AS

BEGIN
    
Insert Into MONEDERO
(
    SALDO,
    NUM_CODIGO,
    IMG_CODIGO
	
)

Values

(
	@SALDO,
	@NUM_CODIGO,
	@IMG_CODIGO
)

END

GO

----------------------------------
---INSERCION DE DATOS ESTATICOS---
----------------------------------

INSERT INTO ESCUELAS (NOMBRE)
VALUES ('Cecyt 13 "Ricardo Flores Magon"')

GO

