CREATE DATABASE GUARDLLET 
GO

USE GUARDLLET
GO

CREATE TABLE ESCUELAS(
	ID_ESCUELA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100)
)

CREATE TABLE DATOS_ESCOLARES(
	ID_DATOS_ESCOLARES INT IDENTITY(1,1) PRIMARY KEY,
	ID_ESCUELA INT,
	BOLETA VARCHAR(10),
	GRUPO VARCHAR(6),
	EDAD VARCHAR(2)
	
	CONSTRAINT fk_ESC FOREIGN KEY (ID_ESCUELA) REFERENCES ESCUELAS(ID_ESCUELA),
)

CREATE TABLE DATOS_GENERALES(
	ID_DATOS_GENERALES INT IDENTITY(1,1) PRIMARY KEY,
	ID_DATOS_ESCOLARES INT NULL,
	NOMBRES VARCHAR(100),
	APELLIDO_P VARCHAR(50),
	APELLIDO_M VARCHAR(50),
	CELULAR VARCHAR(10),
	FOTO IMAGE,
	
	CONSTRAINT fk_DAT_ESC FOREIGN KEY (ID_DATOS_ESCOLARES) REFERENCES DATOS_ESCOLARES(ID_DATOS_ESCOLARES),
)

CREATE TABLE MONEDERO(
	ID_MONEDERO INT IDENTITY(1,1) PRIMARY KEY,
	CODIGO VARCHAR(20),
	IMAGEN_CODIGO IMAGE,
	SALDO INT,
)

CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	ID_DATOS_GENERALES INT NULL,
	ID_MONEDERO INT NULL,
	CORREO VARCHAR(100),
	CONTRASEÑA VARCHAR(MAX),
	TIPO_USUARIO INT,
	ESTADO INT,
	
	CONSTRAINT fk_DAT_GEN FOREIGN KEY (ID_DATOS_GENERALES) REFERENCES DATOS_GENERALES(ID_DATOS_GENERALES),
	CONSTRAINT fk_MON FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO(ID_MONEDERO),
)

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	CODIGO VARCHAR(10),
	PRECIO INT,
	IMAGEN IMAGE,
)

CREATE TABLE MOVIMIENTO_CV(
	ID_MOVIMIENTO_CV INT IDENTITY(1,1) PRIMARY KEY,
	ID_PRODUCTO INT,
	ID_VENDEDOR INT,
	ID_MONEDERO INT NULL,
	ESTADO INT,
	FECHA DATETIME,
	NUMERO_AUTORIZACION VARCHAR(50) NULL,
	MENSAJE VARCHAR(500),
	
	CONSTRAINT fk_PRO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
	CONSTRAINT fk_VEN FOREIGN KEY (ID_VENDEDOR) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT fk_MON_MOV_CV FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO(ID_MONEDERO),
)

CREATE TABLE MOVIMIENTO_R(
	ID_MOVIMIENTO_R INT IDENTITY(1,1) PRIMARY KEY,
	ID_ADMINISTRADOR INT,
	ID_MONEDERO INT NULL,
	MONTO INT,
	FECHA DATETIME,
	ESTADO INT,
	MENSAJE VARCHAR(500),
	
	CONSTRAINT fk_ADM FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT fk_MON_MOV_R FOREIGN KEY (ID_MONEDERO) REFERENCES MONEDERO(ID_MONEDERO),
)

CREATE TABLE COMPROBANTE(
	ID_COMPROBANDE INT IDENTITY(1,1) PRIMARY KEY,
	FECHA DATETIME,
	NOMBRE_ARTICULO VARCHAR(100),
	PRECIO INT,
	TIPO INT,
	NUMERO_AUTORIZACION VARCHAR(50),
)

GO

CREATE PROCEDURE [dbo].[RegistroUsuario]

@CORREO VARCHAR(100),
@CONTRASEÑA VARCHAR(MAX),
@TIPO_USUARIO INT,
@ESTADO INT,
@ID_REGISTRO INT OUTPUT

AS

BEGIN
    
Insert Into USUARIO
(
	CORREO,
	CONTRASEÑA,
	TIPO_USUARIO,
	ESTADO
)

Values

(
	
	@CORREO,
	ENCRYPTBYPASSPHRASE('password', @CONTRASEÑA),
	@TIPO_USUARIO,
	@ESTADO
)

END

BEGIN

DECLARE @ID AS INT 

SELECT @ID = ID_USUARIO FROM USUARIO WHERE CORREO = @CORREO
SET @ID_REGISTRO = @ID

RETURN(@ID_REGISTRO)

END

GO


